# NumPy — Numerical Python

## What is NumPy?

- NumPy stands for **Numerical Python**
- It is a **fast, efficient library** for working with arrays, matrices, and numerical data.
- Used extensively in **data science**, **machine learning**, **scientific computing**.

 Install: `pip install numpy`

---

## Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

## 📌 Import NumPy

```python
import numpy as np

alias: In Python alias are an alternate name for referring to the same thing.





## Create NumPy Arrays

In [2]:
import numpy as np
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
arr = np.array(42)

# 1D array - An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
a = np.array([1, 2, 3])


# 2D array - (matrix)-An array that has 1-D arrays as its elements is called a 2-D array.
b = np.array([[1, 2], [3, 4]])

#3D array - An array that has 2-D arrays (matrices) as its elements is called 3-D array.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


# Array of zeros
z = np.zeros((2, 3))

# Array of ones
o = np.ones((3, 3))

# Range of numbers
r = np.arange(0, 10, 2)

# Evenly spaced numbers
l = np.linspace(0, 1, 5)


## Array Properties

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)   #returns a tuple with each index having the number of corresponding elements.
print("Size:", arr.size)
print("Data Type:", arr.dtype)  #returns the data type of the array
print("Dimensions:", arr.ndim)  # how many dimensions the array have.


Shape: (2, 3)
Size: 6
Data Type: int64
Dimensions: 2


## Data Types in NumPy

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )


## Array Indexing & Slicing
Array indexing is the same as accessing an array element.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.




In [4]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])      # First element
print(a[1:4])    # Slice

# 2D slicing
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b[1])       # Second row
print(b[1, 0])    # Element at row 1, col 0
#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step].





10
[20 30 40]
[3 4]
3


## Array Operations

In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)     # Add
print(x * y)     # Multiply element-wise
print(x ** 2)    # Square


[5 7 9]
[ 4 10 18]
[1 4 9]


## Useful NumPy Functions

In [6]:
a = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Max:", np.max(a))
print("Min:", np.min(a))
print("Standard Deviation:", np.std(a))


Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951


## Reshape and Flatten
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

reshaped = arr.reshape((3, 2))
flattened = arr.flatten()  #Flattening array means converting a multidimensional array into a 1D array.




## Broadcasting

In [8]:
a = np.array([1, 2, 3])
b = 2
print(a * b)  # Multiplies each element by 2


[2 4 6]


## Practice Examples

In [9]:
# 1. Create a 4x4 identity matrix
np.eye(4)

# 2. Replace even numbers in an array with -1
arr = np.array([1, 2, 3, 4, 5, 6])
arr[arr % 2 == 0] = -1

# 3. Reverse a NumPy array
np.array([1, 2, 3])[::-1]



array([3, 2, 1])

## Summary Table

| Task               | Function/Method                   |
| ------------------ | --------------------------------- |
| Create array       | `np.array()`                      |
| Zeros/ones/range   | `np.zeros()`, `np.arange()`       |
| Shape/size         | `.shape`, `.size`                 |
| Math ops           | `+`, `*`, `np.sum()`, `np.mean()` |
| Index/slice        | `arr[1:3]`, `arr[1, 2]`           |
| Reshape/flatten    | `.reshape()`, `.flatten()`        |
| Identity matrix    | `np.eye(n)`                       |
| Conditional select | `arr[arr > 2]`                    |


✅ NumPy is the backbone of numerical computing in Python — fast, efficient, and essential for data analysis, ML, and beyond!