In [ ]:
NumPy Workout Questions
1. Create a 1D NumPy array of numbers from 0 to 9.
2. Create a 3×3 NumPy array with all elements as True.
3. Create a 4×4 identity matrix.
4. Generate a NumPy array of 5 random integers between 10 and 50.
5. Reshape a 1D array of size 9 into a 3×3 matrix.
6. Get the maximum and minimum values from a given NumPy array.
7. Replace all even numbers in an array with -1.
8. Flatten a 2D array to 1D.
9. Find the mean, median, and standard deviation of a NumPy array.
10. Check if any or all elements in a boolean array are True.


In [1]:
import numpy as np

In [13]:
#Create a 1D NumPy array of numbers from 0 to 9.
a=np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#Create a 1D NumPy array of numbers from 0 to 9.
a=np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#Create a 3×3 NumPy array with all elements as True.
a=np.ones((3,3))
a>=1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
#Create a 3×3 NumPy array with all elements as True.
a=np.full((3,3),True)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
#Create a 4×4 identity matrix.
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#Generate a NumPy array of 5 random integers between 10 and 50.
a=np.random.randint(10,51,size=5)
a

array([23, 13, 16, 44, 43], dtype=int32)

In [30]:
#Reshape a 1D array of size 9 into a 3×3 matrix.
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
#Get the maximum and minimum values from a given NumPy array.
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
a.min()

np.int64(10)

In [38]:
a.max()

np.int64(19)

In [46]:
#Replace all even numbers in an array with -1.
a=np.array([0,9,5,8,6,2,4])
a[a%2==0]=-1
a

array([-1,  9,  5, -1, -1, -1, -1])

In [49]:
# Flatten a 2D array to 1D.
a=np.array([[1,2,3],[1,5,6]])
a.ndim


2

In [56]:
b=a.flatten()
b

array([1, 2, 3, 1, 5, 6])

In [57]:
b.ndim

1

In [58]:
#Find the mean, median, and standard deviation of a NumPy array.
a=np.array([[1,2,3],[1,5,6]])
a.mean()

np.float64(3.0)

In [61]:
a.std()

np.float64(1.9148542155126762)

In [64]:
np.median(a)

np.float64(2.5)

In [ ]:
#Check if any or all elements in a boolean array are True.
